Repository AthleteX-DAO/ax_dapp, pull requests merged in 2022-03, with the labels that each got.

#267 Ax 345 0.3 / Ax 372 on Jira - Make Pool Page Responsive
  lib/pages/DesktopPool.dart
  lib/service/AthleteApi.dart
  lib/service/Dialog.dart
Labels: enhancement, mobile

#259 Ax 351 0.3 - Make Trade Page Responsive
  assets/images/Polygon_Small.png
  assets/images/SX_Small.png
  assets/images/X_Logo_Black_BR.png
  lib/pages/DesktopTrade.dart
  lib/service/AthleteTokenList.dart
  lib/service/Dialog.dart
  pubspec.yaml
Labels: enhancement, mobile

#272 Ax 377 frontend farm page dialog needs to be fixed
  assets/images/x.jpg
  lib/pages/DesktopFarm.dart
  lib/service/Dialog.dart
  pubspec.yaml
Labels: enhancement, mobile, frontend

#271 Ax 381 need separate token icons for long short athlete tokens
  lib/pages/DesktopPool.dart
  lib/pages/DesktopTrade.dart
  lib/service/AthleteTokenList.dart
  lib/service/Controller/Scout/LSPController.dart
  lib/service/Controller/Swap/AXT.dart
Labels: smart contract

#279 Ax 394 block selected token from list on swap and pool page
  lib/pages/DesktopTrade.dart
Labels: frontend

#283 Ax 391 pool page being able to create pairs
  lib/pages/DesktopPool.dart
  lib/pages/DesktopTrade.dart
  lib/pages/V1App.dart
  lib/service/ApproveButton.dart
  lib/service/Controller/Pool/PoolController.dart
  lib/service/Controller/Swap/SwapController.dart
  lib/service/Dialog.dart
Labels: smart contract

#285 Ax 394 block selected token from list on swap and pool page
  lib/pages/DesktopTrade.dart
  pubspec.lock
Labels: smart contract, frontend
